    NAME = "Courigin"
    START_TIME = " 00:00:00"
    FINAL_TIME = " 23:59:59"
           EST = " Eastern Time (US & Canada)"
           #PST = " Pacific Time (US & Canada)"
           PST = " PST"

     VOTE_UP = "chevron-up"
     VOTED = "chevron-up"
     LIKE = "star-empty"
     LIKED = "star" 